twoja-manufaktura/twoja-manufaktura/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using twoja_manufaktura.DAL;

namespace twoja_manufaktura.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        StoreContext db = new StoreContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details(int id)
        {
            var product = db.Products.Find(id);
            return View(product);
        }
        public ActionResult List(string genrename, string searchQuery = null)
        {

            var kategoria = db.Kategorie.Include("Products").Where(g => g.Name.ToUpper() == genrename.ToUpper()).Single();
            var products = kategoria.Products.Where(p => searchQuery==null ||
                            p.Name.ToLower().Contains(searchQuery.ToLower()) ||
                            p.Description.ToLower().Contains(searchQuery.ToLower()) 
                            && !p.IsHidden);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductList", products);
            }
            return View(products);
        }
        [ChildActionOnly]
        [OutputCache(Duration =  3600*24*7)]
        //Cachowanie pierwszy argument jest domyślny, można zmienić przechowywanie na serwer albo klienta,
        //Drugi argument to czas przechowywania w sekundach
        public ActionResult GenresMenu()
        {
            var kategorie = db.Kategorie.ToList();
            return PartialView("_GenresMenu", kategorie);
        }

        public ActionResult ProductsSuggestions(string term)
        {
            //zwraca maks. 5 wyników pasujących w filtrowaniu w formacie json zgodnie z doc JQueryUI
            var products = this.db.Products.Where(p => p.Name.ToLower().Contains(term.ToLower()) && !p.IsHidden).Take(5).Select(p => new { label = p.Name });
            return Json(products, JsonRequestBehavior.AllowGet);
        }

    }
}

twoja-manufaktura/twoja-manufaktura/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace twoja_manufaktura.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

twoja-manufaktura/twoja-manufaktura/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

twoja-manufaktura/twoja-manufaktura/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="handmade" content="">
    <meta name="Piotr Migdalski" content="">
    <title>@ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Templates/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="~/Views/Shared/vendor/jquery/jquery.min.js"></script>
    <script src="~/Views/Shared/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="~/Templates/Site.css">
    @System.Web.Optimization.Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <header>
        <div style="overflow: auto;">
            <a id="facebook-header" href="">
                DOŁĄCZ DO NAS NA FACEBOOK
            </a>
            <a id="cart-header-link" href="">
                KOSZYK (<span>@Html.Action("LiczbaRzeczyWKoszyku", "Koszyk")</span>)
                <span></span>
            </a>
        </div>
    </header>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Twoja Manufaktura</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <li class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("StaticContent", "Home", new { viewname = "about" })">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("StaticContent", "Home", new { viewname = "contact" })">Contact</a>
                    </li>
                    <li class="nav-item">
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new {id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ActionLink(User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { @class = "nav-link", title = "Manage" })
                                <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>


                            }
                        }
                        else
                        {
                            @Html.ActionLink("Rejestracja", "Register", "Account", routeValues: null, htmlAttributes: new { @class = "nav-link",id = "registerLink" })
                            @Html.ActionLink("Zaloguj", "Login", "Account", routeValues: null, htmlAttributes: new { @class = "nav-link",id = "loginLink" })

                        }
                    </li>
                    </ul>
            </li>
    </div>
    </nav>
    <div style="margin-top: 30px;"></div>
    @RenderBody()

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy;Twoja Manufaktura</p>
        </div>
        <!-- /.container -->
    </footer>
    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

twoja-manufaktura/twoja-manufaktura/Views/Shared/_ManageLayout.cshtml
@using Microsoft.AspNet.Identity﻿
<!DOCTYPE html>

<html>
<head>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="handmade" content="">
        <meta name="Piotr Migdalski" content="">
        <title>@ViewBag.Title</title>

        <!-- Bootstrap core CSS -->
        <link href="~/Templates/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <script src="~/Views/Shared/vendor/jquery/jquery.min.js"></script>
        <script src="~/Views/Shared/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="~/Templates/Site.css">
        @System.Web.Optimization.Styles.Render("~/Content/themes/base/css")
    </head>
    <style>
        .manageLink {
            height: 42px;
            float: left;
            line-height: 40px;
            font-size: 14px;
            padding-left: 40px;
            /*background-color: #585858;*/
            background-color: #39312E;
            color: white;
        }

        a.manageLink, a.manageLink:hover, a.manageLink:visited {
            color: white;
        }
    </style>
</head>
<body >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Twoja Manufaktura</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <li class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("StaticContent", "Home", new { viewname = "index" })">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("StaticContent", "Home", new { viewname = "about" })">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("StaticContent", "Home", new { viewname = "contact" })">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("OrdersList", "Manage")" style="width: 100px">Zamówienia</a>
                    </li>
                    <li class="nav-item">
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ActionLink(User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { @class = "nav-link", title = "Manage" })
                                <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>


                            }
                        }
                        else
                        {
                            @Html.ActionLink("Rejestracja", "Register", "Account", routeValues: null, htmlAttributes: new { @class = "nav-link", id = "registerLink" })
                            @Html.ActionLink("Zaloguj", "Login", "Account", routeValues: null, htmlAttributes: new { @class = "nav-link", id = "loginLink" })

                        }
                    </li>
                    <li class="nav-item">
                        @if (@User.IsInRole("Admin"))
                        {
                            <a class="nav-link" href="@Url.Action("DodajProdukt", "Manage")">
                                Dodaj Produkt
                            </a>
                        }
                    </li>
                </ul>
            </li>

        </div>
    </nav>
    <div style="overflow: hidden; margin-bottom: 30px;">
        <a id="cart-header-link" href="@Url.Action("Index", "Koszyk")">
            KOSZYK (<span id="cart-header-items-count">@Html.Action("LiczbaRzeczyWKoszyku", "Koszyk")</span>)
            <span id="cart-header-logo"></span>
        </a>
    </div>

    @RenderBody()


    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy;Twoja Manufaktura</p>
        </div>
        <!-- /.container -->
    </footer>

    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

twoja-manufaktura/twoja-manufaktura/Views/Shared/_PartialView.cshtml
@using Microsoft.AspNet.Identity

<div id="login-header">
    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()

            <div>
                @Html.ActionLink(User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })

            </div>
            <div>
                <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>
            </div>
        }
    }
    else
    {
        <div>
            @Html.ActionLink("Rejestracja", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
        </div>
        <div>
            @Html.ActionLink("Zaloguj", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
        </div>
    }
</div>

twoja-manufaktura/twoja-manufaktura/Views/Shared/_PrawyLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">
        <div class="row">
            @Html.Action("GenresMenu", "Store")
            <div class="col-lg-9">
                <div id="productlist-content">
                    <div id="productlist-rightsection">
                        <div id="breadcrumb-section">
                            <img src="@Url.Content("~/Content/Icons/64/iconmonstr-home-1-64.png")" />
                            @Html.MvcSiteMap().SiteMapPath()
                        </div>
                        <section class="content-section">
                            <div class="section-header">
                                <h1>
                                    @RenderSection("Tytul", required: false)
                                </h1>
                            </div>
                            @RenderBody()
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>

@section ScriptsBottom
{
   @RenderSection("ScriptsBottom", required: false)
}

twoja-manufaktura/twoja-manufaktura/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}